services:
  slideprof:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8000
        published: 8000
    #deploy:
    #  resources:
    #    reservations:
    #      memory: 256M